service: cobyo-video-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  websocketsApiName: cobyo-video-sockets
  websocketsApiRouteSelectionExpression: $request.body.action
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:BatchGetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
    Resource: "arn:aws:dynamodb:us-east-1:213475654097:table/Tables"
  - Effect: "Allow"
    Action:
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
    Resource: "arn:aws:dynamodb:us-east-1:213475654097:table/Transcripts"
  - Effect: "Allow"
    Action:
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:BatchGetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
    Resource: "arn:aws:dynamodb:us-east-1:213475654097:table/Users"
  - Effect: "Allow"
    Action:
      - dynamodb:Query
    Resource: "arn:aws:dynamodb:us-east-1:213475654097:table/Users/index/FacebookUserIndex"
  - Effect: "Allow"
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
    Resource: "arn:aws:dynamodb:us-east-1:213475654097:table/ActiveUsers"
  - Effect: "Allow"
    Action:
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:us-east-1:213475654097:table/ChatConnections"
  - Effect: "Allow"
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
    Resource: "arn:aws:dynamodb:us-east-1:213475654097:table/ChatMessages"
  - Effect: "Allow"
    Action:
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:us-east-1:213475654097:table/ChannelConnections"
  - Effect: "Allow"
    Action:
      - dynamodb:Query
    Resource: "arn:aws:dynamodb:us-east-1:213475654097:table/ChannelConnections/index/ConnectionChannelIndex"

functions:
  app:
    handler: build/index.expressHandler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  connectionHandler:
    handler: build/websockets.connectionHandler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: build/websockets.defaultHandler
    events:
      - websocket: $default
  channelHandler:
    handler: build/websockets.channelActionHandler
    events:
      - websocket:
          route: sendMessage
      - websocket:
          route: purchaseMenuItem
